### ISSUE TITLE
The mirror class is broken

### ISSUE THREAD

**Issue by clarkwinkelmann** [buseca/patternbolt#5]
I don't need this feature but my IDE spotted an error on line 96 of [patternbolt.scss](https://github.com/buseca/patternbolt/blob/gh-pages/PatternBolt/scss/patternbolt.scss#L96), I now see that GitHub himself signals the error.

trasform should probably be transform. Even with that set I can't get it to work in my browser.

Since the feature is undocumented, I believe it is still in development.

**Comment by dbertella** [comment]
Thanks for the spot, we have removed for now and we'll fix it in the next release.
